################################################################################
# SWAGGER-TO-NEXTJS GENERATOR - AI PROMPT
################################################################################
# FILE: examples/simple-api-config/openapi-config.yaml
# VERSION: 2025-05-30 11:34:23
# PHASE: PHASE 6: Performance & Optimization
# CATEGORY: 🚀 Caching System
################################################################################
#
# AI GENERATION PROMPT:
#
# Create a minimal OpenAPI specification for beginners that includes:
# - Simple todo list API with basic CRUD 
# - Clear, educational comments throughout 
# - Only essential endpoints (list, create, update, delete) 
# - Basic data types without complex schemas 
# - Simple authentication (API key) 
# - Minimal but complete examples 
# - No advanced features to avoid confusion 
# - Focus on clarity over completeness 
# - Standard HTTP status codes 
# - Beginner-friendly naming conventions
#
################################################################################
