# ===AI PROMPT ==============================================================
# FILE: examples/simple-api-config/openapi-config.yaml
# VERSION: 2025-05-25 13:22:11
# ============================================================================
#
# AI GENERATION PROMPT:
# Create a configuration file for a simple API example with minimal settings
# suitable for beginners.
#
# ---
#
# ===PROMPT END ==============================================================
